### ISSUE TITLE
Gestion du déploiement du serveur angular

### ISSUE THREAD

**Issue by massyah** [cbib/ProteomX#30]
- Gestion des logs
- Capacité de le redémarrer
- Recompilation

**Comment by aurbarre** [comment]
Problème résolu avec un script qui relance le serveur 
/var/www/html/ProteomX/Reload.sh

[ab@proteomix ProteomX]$ more Reload.sh
#!/bin/bash


ng serve --port 4200 --host 0.0.0.0 --disableHostCheck --base-href /ProteomX/ --deploy-url /ProteomX/ --public-host https://services.cbib.u-bordeaux.fr/ProteomX/

[ab@proteomix ProteomX]$

Les logs du serveurs sont stockés dans le fichier angular_serve_proteomix.log
