### ISSUE TITLE
rajouter dans l'output d'analyse les protéines exclues

### ISSUE THREAD

**Issue by massyah** [cbib/ProteomX#41]

**Comment by massyah** [comment]
* Nom 
* Raison d'exclusion

**Comment by tigloo123** [comment]
Rajouter une colonne "1/0" (quelle protéine est gardée / non gardée)

**Comment by massyah** [comment]
Renvoyer au front un fichier complet avec toutes les observations + une colonne indiquant exclusion et raison d'exclusion
